# Generated by Django 5.2.4 on 2025-07-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('manage_inventory', 'Can manage inventory'), ('manage_sales', 'Can manage sales')]},
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Can manage inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_sales',
            field=models.BooleanField(default=False, help_text='Can manage sales'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_dashboard',
            field=models.BooleanField(default=False, help_text='Can access dashboard'),
        ),
    ]
